services:
  daphne:
    build: .
    working_dir: /code
    command: ["./wait-for-it.sh", "db:5432", "--", 
              "daphne", "-b", "0.0.0.0", "-p", "9001", 
              "educa.asgi:application"]
    restart: always
    volumes:
      - .:/code
      - ./wait-for-it.sh:/code/wait-for-it.sh
    environment:
      DJANGO_SETTINGS_MODULE: educa.settings.prod
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
      - cache
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: educa
      POSTGRES_USER: shenlee
      POSTGRES_PASSWORD: "shenlee@53"
  cache:
    image: redis:7.0.11
    restart: always
    volumes:
      - ./data/redis:/data

  web:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 -- uwsgi --ini /code/config/uwsgi/uwsgi.ini"
    restart: always
    volumes:
      - .:/code
      - ./wait-for-it.sh:/code/wait-for-it.sh
    environment:
      DJANGO_SETTINGS_MODULE: educa.settings.prod
      POSTGRES_DB: educa
      POSTGRES_USER: shenlee
      POSTGRES_PASSWORD: "shenlee@53"
    depends_on:
      - db
      - cache
  nginx:
    image: nginx:1.25.5
    restart: always
    depends_on:
      - web
      - daphne
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"
  # certbot:
    # image: certbot/certbot
    # volumes:
     #  - ./certbot/www:/var/www/certbot
      # - ./certbot/conf:/etc/letsencrypt
    # command: certonly --webroot --webroot-path=/var/www/certbot -d educaproject.com -d www.educaproject.com --email your@email.com --agree-tos --non-interactive
    
    
