services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: educa
      POSTGRES_USER: shenlee
      POSTGRES_PASSWORD: "shenlee@53"
  cache:
    image: redis:7.0.11
    restart: always
    volumes:
      - ./data/redis:/data

  web:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 -- uwsgi --ini /code/config/uwsgi/uwsgi.ini"
    restart: always
    volumes:
      - .:/code
      - ./wait-for-it.sh:/code/wait-for-it.sh
    environment:
      DJANGO_SETTINGS_MODULE: educa.settings.prod
      POSTGRES_DB: educa
      POSTGRES_USER: shenlee
      POSTGRES_PASSWORD: "shenlee@53"
    depends_on:
      - db
      - cache
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
    
    
